### PR TITLE
Change adze to jingle

### PR DESCRIPTION
**Pull request by gcampo88**
Addresses #33. Also a good opportunity to do a high-level review of general API design and schema.

### CODE REVIEW

**Review by cavis — CHANGES_REQUESTED** [review]
The rename looks good to me.  But I'm having issues getting this to build/run with docker (and it appears codebuild is as well).  I always end up with a loop of "waiting for postgres".  Are things currently working for you?

May just need a few updates to get `mix test` to pass.

**Comment by gcampo88** [comment]
Huh... everything is working for me fine locally through docker, though I can see that it's not working in Codebuild. Which commands send you into a `Waiting for postgres` loop? Going to add LOCAL_ENV -> true in docker-compose.yml, possible it wasn't getting that value correctly before...

**Comment by cavis** [comment]
Okay, so summary of changes this may or may not need to work in CodeBuild / ECS ...

- [x] Add `POSTGRES_USER` and `POSTGRES_PASSWORD` to the env-example
- [x] Add `RELX_REPLACE_OS_VARS` to the dockerfile
- [x] Add the `|| "${ENV_VAR_NAME}"`s to the config.exs
- [x] Find/replace "porter" -> "jingle" (must be leftover in castle as well)
- [x] Don't actually need `docker-compose start db` step in the README (i think it just auto-starts the db)
- [x] For ID_HOST to work, you need to define a `config :jingle, :env_config, ...` in your config.exs, as Env.get tries to pull from that
- [x] Instead of using an `.env`, your docker-compose-ci.yml should just define all the ENVs inline (see feeder + castle for example) ... or just use the env-example

**Comment by cavis** [comment]
:+yay: that'll do, PR.  that'll do.

**Review by cavis — APPROVED** [review]

**Pull request merged**
