### PR TITLE
Make local dotenv work

### PR DESCRIPTION
**Pull request by cavis**
Forever.

### CODE REVIEW

**Comment by gcampo88** [comment]
oops, build failed!
```
** (UndefinedFunctionError) function Dotenv.load!/0 is undefined (module Dotenv is not available)
Dotenv.load!()
```

**Comment by cavis** [comment]
Oh right, that's only going to work in dev.

**Comment by cavis** [comment]
Okay, this _should_ compile, but still produces a `warning: function Dotenv.load!/0 is undefined` in prod.  Will think about how to work around that.

**Review by gcampo88 — APPROVED** [review]
LGTM! 🌮 @cavis !

**Pull request merged**
